### PR TITLE
Show errors when loading track

### PR DESCRIPTION
**Pull request by iva2k**

### CODE REVIEW

**Review by walmik — APPROVED** [review]
Thank you @iva2k !

**Comment by iva2k** [comment]
thanks for quick review / merge! That encourages submitting more fixes.

I have few quick questions - where is best to chat? (open issue here, slack, or something else?)

**Comment by walmik** [comment]
Hello @iva2k ! Opening issues is fine as well OR if you like we can use the Scribbletune Discord channel. It s not very active at the moment but might be a good way to chat more real time https://discord.com/channels/743500905051193424/743500905508372653

**Comment by iva2k** [comment]
The link did not let me in (invite link is needed). So I googled and found an active invite link - I'm in!

**Comment by walmik** [comment]
Apologies for the wrong link! Glad you still made it :D

**Pull request merged**
